### ISSUE TITLE
How to correctly estimate 'rate' in each report?

### ISSUE THREAD

**Issue by JoeyYoung** [ccp-project/portus#101]
Hi all,

I did some tests based on const.py to enable a fixed sending rate.
The NIC I use is 1Gbps, the os kernel version is 5.4.0.
One machine serves as a server `iperf -s`, one client machine sends data `iperf -c xxx -Z ccp`. 

In the datapath program, I defined the rate field in a similar way with your bbr implementation:
```
(:= Report.rate (max Report.rate (min Flow.rate_outgoing Flow.rate_incoming)))
```
The report will be returned to user space in every 100ms.

I found that the rate reported has a large gap with the sending rate I defined. I understand that bias exists since it's only an estimation, but the weird thing is that: a larger sending rate doesn't ensure a larger _Report.rate_. For example, if I define the sending rate to be 240Mbps, the reported rate shows around 600Mbps; but when I define the sending rate to be 320Mbps, the reported rate shows only around 460Mbps.

This inaccurate rate estimation even makes the bbr algorithm (https://github.com/ccp-project/bbr) perform much worse than default TCP in my machines. I wonder whether it is a bug or there is anything I didn't notice?

And I will really appreciate it if there is any other way to correctly estimate the rate in the datapath program.

The script I use to run:

``` python
import sys
import pyportus as portus

class ConstFlow():
    INIT_RATE = 100000000 # change different specific rates
    INIT_CWND = 10

    def __init__(self, datapath, datapath_info):
        self.datapath = datapath
        self.datapath_info = datapath_info

        self.init_cwnd = float(self.datapath_info.mss * ConstFlow.INIT_CWND)
        self.cwnd = self.init_cwnd

        self.rate = ConstFlow.INIT_RATE
        self.datapath.set_program("default", [("Rate", self.rate), ("Cwnd", int(self.cwnd)*900)])

    def on_report(self, r):
        print("receive report: ", self.datapath_info.sock_id, self.datapath_info.src_ip, self.datapath_info.dst_ip)
        print("rate(Mbps): ", r.rate/125000)

class Const(portus.AlgBase):
    def datapath_programs(self):
        return {
                "default" : """\
                (def (Report
                    (volatile acked 0)
                    (volatile sacked 0)
                    (volatile loss 0)
                    (volatile timeout false)
                    (volatile rtt 0)
                    (volatile inflight 0)
                    (volatile rate 0)
                ))
                (when true
                    (:= Report.inflight Flow.packets_in_flight)
                    (:= Report.rtt Flow.rtt_sample_us)
                    (:= Report.acked (+ Report.acked Ack.bytes_acked))
                    (:= Report.sacked (+ Report.sacked Ack.packets_misordered))
                    (:= Report.loss Ack.lost_pkts_sample)
                    (:= Report.timeout Flow.was_timeout)
                    (:= Report.rate (max Report.rate (min Flow.rate_outgoing Flow.rate_incoming)))
                    (fallthrough)
                )
                (when (> Micros 100000)
                    (report)
                    (:= Micros 0)
                )
            """
        }

    def new_flow(self, datapath, datapath_info):
        print("receive new flow: ", datapath_info.sock_id, datapath_info.src_ip, datapath_info.dst_ip)
        return ConstFlow(datapath, datapath_info)

alg = Const()

portus.start("netlink", alg)
```

**Comment by akshayknarayan** [comment]
Hi,
I ran the code you provided on my machine (also kernel 5.4), and got output like this (I used an emulated mahimahi link):
```
receive report:  1 67125348 16793700
rate(Mbps):  95.855592
receive report:  1 67125348 16793700
rate(Mbps):  96.631464
receive report:  1 67125348 16793700
rate(Mbps):  97.130816
receive report:  1 67125348 16793700
rate(Mbps):  96.142224
receive report:  1 67125348 16793700
rate(Mbps):  97.12692
receive report:  1 67125348 16793700
rate(Mbps):  97.15564
receive report:  1 67125348 16793700
rate(Mbps):  98.776592
receive report:  1 67125348 16793700
rate(Mbps):  94.295688
receive report:  1 67125348 16793700
rate(Mbps):  98.565568
```

As you noted, there are any number of reasons why rate measurement may be inaccurate on your machine. I would suggest trying in an emulated link first. Ultimately, we depend on the kernel's rate estimates (we use the same as the kernel BBR implementation, see here: https://github.com/ccp-project/ccp-kernel/blob/master/tcp_ccp.c#L190), so if those have significant noise then there is not much we can do.

**Comment by JoeyYoung** [comment]
Hi,
Thanks for your output in an emulated link. As you can see in my script, the applied rate is `INIT_RATE = 100000000`, which is 100*e6 (byte per second) and equals to 800 Mbps. But the reported rate in your output is only around 95Mbps, the gap is too large.

**Comment by akshayknarayan** [comment]
Should have mentioned earlier - the emulated link was 96Mbps, so this is expected. If I remove a zero from `INIT_RATE` in your script, i.e. setting the pacing rate to 80Mbps:

```receive report:  1 67125348 16793700
rate(Mbps):  83.333328
receive report:  1 67125348 16793700
rate(Mbps):  83.711832
receive report:  1 67125348 16793700
rate(Mbps):  83.793736
receive report:  1 67125348 16793700
rate(Mbps):  84.023936
receive report:  1 67125348 16793700
rate(Mbps):  83.795344
receive report:  1 67125348 16793700
rate(Mbps):  83.377384
```
