### ISSUE TITLE
Can CCP change packet format and parse information in the packet header?

### ISSUE THREAD

**Issue by Clark5** [ccp-project/portus#102]
Any comment can be helpful!

**Comment by akshayknarayan** [comment]
No. CCP only implements congestion control given a standard set of measurements; it is not a packet processing system (and, given its goal to be compatible across various datapaths and protocols, e.g. TCP, QUIC, etc, it's not clear how this would even work).

If you want to use custom header fields in a CCA implementation, you should probably fork CCP to implement your specialized packet processing and add your new custom measurement field [here](https://github.com/ccp-project/libccp/blob/master/ccp.h#L24) and [here](https://github.com/ccp-project/portus/blob/master/src/lang/datapath.rs#L474), then calculate it in a function similar to this one: https://github.com/ccp-project/ccp-kernel/blob/master/tcp_ccp.c#L155.

Hope this helps.
