### ISSUE TITLE
Remove submodules

### ISSUE THREAD

**Issue by fcangialosi** [ccp-project/portus#19]
We currently have `libccp` and `ccp-kernel` (which also submodules `libccp`) as submodules in this repo purely for the purpose of integration testing. This causes a bit of a headache when we make changes in libccp and everything has to be propagated up. I think it would be just as good (and remove the dependencies) if we instead created a script that just git clones the repos when the integration test is run, rather than explicitly having them as submodules. Travis CI will still work essentially the same, just the repo won't specifically track the submodules. Should be a simple change.

**Comment by akshayknarayan** [comment]
A potential problem is differences in commit compatibility. With submodules, if there are breaking api changes then each commit can still be tested independently, but with a script we'd have to be careful to clone exact "fake-submodule" commits. In fact I'm pretty sure this is why submodules exist in the first place :)

**Comment by fcangialosi** [comment]
I agree, that’s a fair point, but at least at this stage the sub modules are changing almkst everyday so it’s a bit annoying, especially when we have to wait for pull request approval for little things

**Comment by fcangialosi** [comment]
@akshayknarayan -- how about this.. since we're actively doing a lot of development right now, until sigcomm we remove the submodules and change it to just checkout the latest copy of the repos (it doesn't need to track a specific version, which would defeat the point obviously). when sigcomm rolls around everything should be more stable and we can switch it back to submodules which is a bit more robust.
