### ISSUE TITLE
Initial communication with datapath

### ISSUE THREAD

**Issue by fcangialosi** [ccp-project/portus#2]
It may be useful for the the CCP and datapath to briefly exchange messages when the CCP is first started to:
1. Allow the CCP to set a backup algorithm in the datapath in case the CCP crashes / datapath is no longer able to communicate with the CCP
2. Allow the datapath to communicate which features it supports and the CCP to handle this accordingly (e.g. the algorithm could check for a list of features it needs and exit if the selected datapath doesn't provide these)

This would involve adding a new message type..

**Comment by akshayknarayan** [comment]
Relatedly, we might want to consider adding functionality for a "default fold function" that doesn't require any interaction at all (no need to wait for the "create" message)

**Comment by deeptir18** [comment]
Also, it would be nice if there were  a version check between portus and libccp in this startup message.

**Comment by akshayknarayan** [comment]
Closing in favor of #32
