### ISSUE TITLE
Potential bug of stuck

### ISSUE THREAD

**Issue by mafen408** [ccp-project/portus#73]
I have been testing BBR (update branch) and found that BBR always got stuck (no more console outputs) some time after beginning. 
For example, 

Jan 23 09:26:02.768 INFO switching to PROBE_BW, min rtt (us): 41764, Rate (5/4): 1.25, bottle rate (Mbps): 1, Rate (3/4): 0.75, cwnd: 10441
Jan 23 09:26:02.768 INFO PROBE_RTT, min_rtt (us): 41764
Jan 23 09:26:05.258 INFO probe_bw, bottle rate (Mbps): 1, rate (Mbps): 0, elapsed: 0.522
Jan 23 09:26:05.258 INFO new min_rtt, bottle rate: 1, min_rtt (us): 196893
Jan 23 09:26:05.259 INFO new_flow
Jan 23 09:26:05.259 INFO switching to PROBE_BW, min rtt (us): 196893, Rate (5/4): 1.25, bottle rate (Mbps): 1, Rate (3/4): 0.75, cwnd: 49223

after 09:26:05, I got no more outputs.

After tracing down the flow, I found the stuck point always at the "send_msg(&buf[..])" function. Specifically, it is either at
portus->lib.rs->set_program->self.sender.send_msg(&buf[..])?; (around line 186)
or
portus->lib.rs->update_field->self.sender.send_msg(&buf[..])?; (around line 230).

This is identified by adding println! lines in the files, the output of which is as below:
Jan 23 16:14:53.025 INFO new min_rtt, bottle rate: 1, min_rtt (us): 7288
      in portus: while ...........
          in portus: new measurement ...........
in bbr: on_report--------------------
in bbr, on_report: ProbeBw --------------------
in bbr, on_report: ProbeBw, before init --------------------
in bbr: install_probe_bw--------------------
  in portus: update_field .................
Jan 23 16:14  in portus: update_field, before send_msg, buf: [3, 0, 38, 0, 59, 0, 0, 0, 2, 0, 0, 0, 2, 4, 0, 0, 0, 101, 255, 0, 0, 0, 0, 0, 0, 2, 5, 0, 0, 0, 90, 98, 2, 0, 0, 0, 0, 0]
:53.040 INFO probe_bw, bottle rate (Mbps): 1, rate (Mbps): 0, elapsed: 0.717
Jan 23 16:14:53.041 INFO new min_rtt, bottle rate: 1, min_rtt (us): 261525
Jan 23 16:14:53.041 INFO new_flow
Jan 23 16:14:53.041 INFO switching to PROBE_BW, min rtt (us): 261525, Rate (5/4): 1.25, bottle rate (Mbps): 1, Rate (3/4): 0.75, cwnd: 65381
(then it gets stuck and gives no more output)

I suspect the reason is that the TCP connection is destroyed unexpectedly, e.g. due to timeout. 

Environment:
Ubuntu 18.04, default kernel.
Wireless network connection, unstable.

Hope the team can fix it.
Thanks.

**Comment by akshayknarayan** [comment]
Hello, thanks again for this bug report.
Assuming you are still able to reproduce this, could you provide the contents of `/var/log/syslog` during this experiment?
`send_msg` should not block when the TCP connection is destroyed - ccp-kernel will receive all messages in global scope, and if the resulting connection is not found, the message will be discarded.

**Comment by mafen408** [comment]
Hi, 
Attached please find the syslog file when I run CCP (the program again got stuck at send_msg). 
There are many log lines saying: "libccp: Datapath program is null". 
Please have a check. 

FYI, here is what I did in the experiment:
1. download libccp and put it in the CCP_kernel folder
2. make ccp kernel
3. run sudo ./ccp_kernel_load ipc=0
4. run sudo sysctl -w net.ipv4.tcp_allowed_congestion_control="cubic reno ccp"
5. run sudo sysctl -w net.ipv4.tcp_congestion_control="ccp"
6. in the bbr_update folder, run cargo build --release
7. run sudo ./target/release/bbr --ipc=netlink

Thanks.

[syslog.txt](https://github.com/ccp-project/portus/files/2908223/syslog.txt)

**Comment by akshayknarayan** [comment]
Thank you for the syslog! I will look into this issue.

**Comment by akshayknarayan** [comment]
hello, we have discovered and fixed two bugs in the CCP kernel datapath (https://github.com/ccp-project/ccp-kernel/commit/076b1ee92ee2a19a1f8e8b6e6b94f27bc9d69e4c).
If possible, could you try to reproduce this issue once more?
Thanks!

**Comment by mafen408** [comment]
Sure, shall I use portus v0.5 of the rust crate?

**Comment by akshayknarayan** [comment]
We have not yet updated most algorithms to portus v0.5 - I suggest you use the same algorithm implementations, but with the new version of the kernel module.

**Comment by mafen408** [comment]
Hi, Akshay,
I have updated the libccp with the new files and compiled the kernel. 
After testing bbr for more than 10 minutes (none of the previous stuck cases lasts more than 5 minutes), I have not met the stuck problem (but there are still some kind of errors in the syslog file, see attached). 
Though, I will keep testing until further confirm. 
I have also attached the syslog file, please have a look if needed.
Thanks for the work!

Best regards,
[syslog.txt](https://github.com/ccp-project/portus/files/2979020/syslog.txt)
