### ISSUE TITLE
the question about the aimd demo

### ISSUE THREAD

**Issue by jialianchen** [ccp-project/portus#93]
hello ,i run the aimd demo,but i meet some problem.
```
import sys
import portus

class AIMDFlow():
    INIT_CWND = 10

    def __init__(self, datapath, datapath_info):
        self.datapath = datapath
        self.datapath_info = datapath_info
        self.init_cwnd = float(self.datapath_info.mss * AIMDFlow.INIT_CWND)
        self.cwnd = self.init_cwnd
        self.datapath.set_program("default", [("Cwnd", int(self.cwnd))])

    def on_report(self, r):
        if r.loss > 0 or r.sacked > 0:
            self.cwnd /= 2
        else:
            self.cwnd += (self.datapath_info.mss * (r.acked / self.cwnd))
        print(r.acked)
        print(r.loss)
        print(r.sacked)
        #print(r.inflight)
        #print(r.rtt)
        self.cwnd = max(self.cwnd, self.init_cwnd)
        self.datapath.update_field("Cwnd", int(self.cwnd))


class AIMD(portus.AlgBase):

    def datapath_programs(self):
        return {
                "default" : """\
                (def (Report
                    (volatile acked 0) 
                    (volatile sacked 0) 
                    (volatile loss 0) 
                    (volatile timeout false)
                    (volatile rtt 0)
                    (volatile inflight 0)
                ))
                (when true
                    (:= Report.inflight Flow.packets_in_flight)
                    (:= Report.rtt Flow.rtt_sample_us)
                    (:= Report.acked (+ Report.acked Ack.bytes_acked))
                    (:= Report.sacked (+ Report.sacked Ack.packets_misordered))
                    (:= Report.loss Ack.lost_pkts_sample)
                    (:= Report.timeout Flow.was_timeout)
                    (fallthrough)
                )
                (when (|| Report.timeout (> Report.loss 0))
                    (report)
                    (:= Micros 0)
                )
                (when (> Micros Flow.rtt_sample_us)
                    (report)
                    (:= Micros 0)
                )
            """
        }

    def new_flow(self, datapath, datapath_info):
        return AIMDFlow(datapath, datapath_info)

alg = AIMD()

portus.start("netlink", alg, debug=True)


```
i want to print the rtt and the inflight(although they are not be used in aimd)
the teminal output
```
0
0
10
Traceback (most recent call last):
  File "aimd.py", line 22, in on_report
    print(r.inflight)
Exception: Failed to get inflight: portus err: the requested field is in scope but was not found in the report
ERRO on_report() failed to complete, sid: 1
Jul 15 22:04:35.454 ERRO on_report() failed to complete, sid: 1
Jul 15 22:04:35.455 ERRO on_report() failed to complete, sid: 1
Jul 15 22:04:35.455 ERRO on_report() failed to complete, sid: 1
Jul 15 22:04:35.456 ERRO on_report() failed to complete, sid: 1
Jul 15 22:04:35.456 ERRO on_report() failed to complete, sid: 1
Jul 15 22:04:35.457 ERRO on_report() failed to complete, sid: 1
Jul 15 22:04:35.457 ERRO on_report() failed to complete, sid: 1
Jul 15 22:04:35.458 ERRO on_report() failed to complete, sid: 1
Jul 15 22:04:35.458 ERRO on_report() failed to complete, sid: 1
Jul 15 22:04:35.459 ERRO on_report() failed to complete, sid: 1
Jul 15 22:04:35.459 ERRO on_report() failed to complete, sid: 1
Jul 15 22:04:35.460 ERRO slog-async: logger dropped messages due to channel overflow, count: 1
Jul 15 22:04:35.460 ERRO slog-async: logger dropped messages due to channel overflow, count: 1
```
i do not know the reason why i can print the acked and the loss but i can not print the rtt and the inflight.
Thanks for your help!

**Comment by akshayknarayan** [comment]
Hi,
Could you try using the new version of the python module (in the PR here: https://github.com/ccp-project/portus/pull/95)? Using that (and the latest ccp-kernel), your example works for me.

**Comment by jialianchen** [comment]
Hello ,i use the linux 5.4.0-050400-generic,and i find that i can print the r.rtt and the r.inflight,but i can not print r.rate_incoming.
i follow your guide and use the PR to  create the virtual environment and run  `maturin build` in /home/ubuntu/portus/python and install the result  `pip install /home/ubuntu/portus/python/target/wheel/pyportus-0.5.0-cp36-cp36m-manylinux_2_24_x86_64.whl`.
but after i `maturin develop `and `cd examples && sudo python aimd.py`  ,
i get `  File "aimd.py", line 26, in <module>
    class AIMD(portus.AlgBase):
AttributeError: module 'pyportus' has no attribute 'AlgBase'`
i check the `/home/ubuntu/portus/python/venv/lib/python3.6/site-packages/pyportus`it has `__init__.py  ` `__pycache__  ` `pyportus.cpython-36m-x86_64-linux-gnu.so` it seems correct.
I wonder  whether you can give me some suggestions....

**Comment by akshayknarayan** [comment]
Hi,
The instructions in the PR had a small error: it is supposed to be `cd examples && sudo ./<venv>/python aimd.py`, so in your case it would be (from the examples directory): `sudo RUST_LOG=debug ../bin/python aimd.py`.

This is because you need do be root to run CCP (because it uses netlink), but at the same time the virtualenv is only available for your user. So you need to use sudo but use the virtualenv's python. What is happening in your case is that you have installed the released version of the pyportus package, so `sudo python aimd.py` is using that instead of the one maturin produced.
