### ISSUE TITLE
Where i can find the correct example that can run with mtcp

### ISSUE THREAD

**Issue by JeremyGuo** [ccp-project/portus#97]
Help wanted.

**Comment by akshayknarayan** [comment]
Hi,
CCP support for mTCP was merged some time ago: https://github.com/mtcp-stack/mtcp#ccp-support
You can run a the CCP implementation of a congestion control algorithm the same way as with another datapath. 
Keep in mind that you may need to update mtcp's libccp submodule to the latest version. 

cc @fcangialosi

**Comment by fcangialosi** [comment]
Hi Jeremy,

If you have any trouble running CCP within mTCP, let me know (frankc@csail.mit.edu). 

I'd also recommend using this simple iperf-style app I wrote on top of mTCP for testing purposes: https://github.com/mtcp-stack/mtcp/tree/master/apps/perf
